# Generated by Django 3.2.16 on 2025-04-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.CharField(db_column='documento', max_length=50)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('telefono', models.CharField(db_column='telefono', max_length=100)),
                ('direccion', models.CharField(db_column='direccion', max_length=100)),
                ('correo', models.CharField(db_column='correo', max_length=255)),
                ('usuario_creacion', models.IntegerField(db_column='usuario_creacion')),
                ('usuario_modificacion', models.IntegerField(db_column='usuario_modificacion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_modificacion', models.DateTimeField(db_column='fecha_modificacion', null=True)),
                ('estado', models.CharField(db_column='estado', default='activo', max_length=15)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
    ]
