# Generated by Django 3.2.16 on 2025-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='usuario_modificacion',
            field=models.IntegerField(db_column='usuario_modificacion', null=True),
        ),
    ]
